### ISSUE TITLE
能不能改成异步的呢？

### ISSUE THREAD

**Issue by LztCode** [suparek/rabbitlib#1]
- [ ] 用这个 **pika.SelectConnection** 连接器，大佬带带我，回调太多了，改不动啊

**Comment by suparek** [comment]
> * [ ]  用这个 **pika.SelectConnection** 连接器，大佬带带我，回调太多了，改不动啊

😔我也想，可惜暂时没时间搞这个

**Comment by LztCode** [comment]
> > * [ ]   用这个 **pika.SelectConnection** 连接器，大佬带带我，回调太多了，改不动啊
> 
> 😔我也想，可惜暂时没时间搞这个

大佬我想问一下，生产者怎么通知消费者已经生产完毕，然后消费者退出循环呢，就那个test里面的例子

**Comment by LztCode** [comment]
> > > * [ ]    用这个 **pika.SelectConnection** 连接器，大佬带带我，回调太多了，改不动啊
> > 
> > 
> > 😔我也想，可惜暂时没时间搞这个
> 
> 大佬我想问一下，生产者怎么通知消费者已经生产完毕，然后消费者退出循环呢，就那个test里面的例子

一对多的情况下，多个消费者监听怎么做呢，多进程吗

**Comment by suparek** [comment]
> > > > * [ ]     用这个 **pika.SelectConnection** 连接器，大佬带带我，回调太多了，改不动啊
> > > 
> > > 
> > > 😔我也想，可惜暂时没时间搞这个
> > 
> > 
> > 大佬我想问一下，生产者怎么通知消费者已经生产完毕，然后消费者退出循环呢，就那个test里面的例子
> 
> 一对多的情况下，多个消费者监听怎么做呢，多进程吗

多进程也可以，同时多起几个worker也可以，看你方便.

**Comment by suparek** [comment]
> > > * [ ]    用这个 **pika.SelectConnection** 连接器，大佬带带我，回调太多了，改不动啊
> > 
> > 
> > 😔我也想，可惜暂时没时间搞这个
> 
> 大佬我想问一下，生产者怎么通知消费者已经生产完毕，然后消费者退出循环呢，就那个test里面的例子

还有这种场景？呃，你看是不是在生产完毕之后，再生产一条特异的消息，消费者拿到这条特异的消息后，就退出试试。
